'use strict';

/**
 * Pipeline integration — wrap *existing* admin data functions as Open Admin
 * plugins, without rewriting your admin.
 *
 * A "pipeline" is just a named set of async functions you already have, e.g.
 * Guava.land's `getRecentOrders()` / `getCatalogueProducts()` in
 * `src/lib/data/*.ts`. This module turns each pipeline into:
 *
 *   - a server module  ({ init(ctx) }) that exposes
 *     `GET /api/<plugin>/<resource>/list` (+ optional get/update/create)
 *     backed by your functions, via a `site.data` capability;
 *   - a manifest       ({ id, pages, widgets, … }) for nav + dashboard;
 *   - a client.js      (generated string) rendering mobile-friendly tables
 *     and dashboard summary widgets with the shared `OA` client kernel.
 *
 * Works on plain Node (dirs on disk) AND on bundled/edge runtimes: pass the
 * returned `{ pluginDefs, serverModules, assets }` straight into
 * `createOpenAdmin()` — no `require()`, no filesystem.
 *
 * Example (Guava.land-style):
 *
 *   const { adaptExistingAdmin } = require('open-admin/src/integrations/pipeline');
 *   const { pluginDefs, serverModules, assets } = adaptExistingAdmin({
 *     capabilityName: 'guava.data',
 *     pipelines: [{
 *       id: 'guava-orders', name: 'Guava Orders', icon: '🛒', category: 'General',
 *       page: { path: 'guava-orders', title: 'Orders', order: 10 },
 *       widget: { slot: 'dashboard.grid', id: 'guava-orders-summary', order: 30 },
 *       resources: { orders: { list: (limit) => getRecentOrders(limit), columns: [...] } },
 *     }],
 *   });
 *   await createOpenAdmin({ siteName: 'Guava.land', pluginDefs, serverModules, assets });
 */

function escId(s) {
  return String(s).replace(/[^a-z0-9-]/gi, '-').toLowerCase();
}

/**
 * Build a client.js source string for one pipeline plugin. The generated UI
 * is deliberately mobile-first: tables scroll inside `.oa-table-wrap`,
 * dashboard widgets are single-column cards, and everything uses the shared
 * OA helpers (esc, api, crashCard).
 */
function buildClientJs({ pluginId, page, resources, emptyHint }) {
  const resourceNames = Object.keys(resources);
  const primary = resourceNames[0];
  const pagePath = (page && page.path) || pluginId;
  const pageTitle = (page && page.title) || pluginId;
  return `/** Generated by open-admin pipeline adapter — plugin "${pluginId}". */
export default {
  register(OA) {
    OA.registerPage(${JSON.stringify(pagePath)}, {
      mount(el, OA) {
        const status = document.createElement('div');
        status.innerHTML = '<div class="oa-card"><p class="muted">Loading…</p></div>';
        el.appendChild(status);
        OA.api(${JSON.stringify(`/api/${pluginId}/${primary}/list`)})
          .then(({ items, rows, orders, products, data }) => {
            const list = items || rows || orders || products || data || [];
            if (!list.length) {
              status.innerHTML = '<div class="oa-card"><h3>No rows yet</h3>'
                + '<p class="muted">' + OA.esc(${JSON.stringify(emptyHint || 'This pipeline returned zero rows.')}) + '</p></div>';
              return;
            }
            const keys = Object.keys(list[0] || {}).slice(0, 6);
            const head = keys.map((k) => '<th>' + OA.esc(k) + '</th>').join('');
            const body = list.map((row) => '<tr>' + keys.map((k) => {
              let v = row[k];
              if (v && typeof v === 'object') v = JSON.stringify(v).slice(0, 80);
              if (v === null || v === undefined || v === '') v = '—';
              return '<td>' + OA.esc(String(v)).slice(0, 120) + '</td>';
            }).join('') + '</tr>').join('');
            status.innerHTML =
              '<div class="oa-page-head"><h2>' + OA.esc(${JSON.stringify(pageTitle)}) + '</h2>'
              + '<p>' + list.length + ' rows from your existing pipeline.</p></div>'
              + OA.tableWrap('<table class="oa-table"><thead><tr>' + head + '</tr></thead><tbody>' + body + '</tbody></table>');
          })
          .catch((err) => { status.innerHTML = OA.crashCard(${JSON.stringify(pluginId)}, err.message); });
      },
    });
    OA.registerWidget(${JSON.stringify(`${pluginId}-summary`)}, {
      mount(el, OA) {
        OA.api(${JSON.stringify(`/api/${pluginId}/${primary}/list`)})
          .then(({ items, rows, orders, products, data }) => {
            const list = items || rows || orders || products || data || [];
            el.innerHTML = '<div class="oa-card oa-stat"><span class="num">' + list.length + '</span>'
              + '<span class="lbl">' + OA.esc(${JSON.stringify(pageTitle)}) + '</span>'
              + '<a href="#/' + OA.esc(${JSON.stringify(pagePath)}) + '" style="font-size:13px;font-weight:600">Open →</a></div>';
          })
          .catch((err) => { el.innerHTML = OA.crashCard(${JSON.stringify(pluginId)}, err.message); });
      },
    });
  },
};
`;
}

/**
 * Build a server module for one pipeline plugin. At request time it reads the
 * host data layer through `ctx.capabilities.use(capabilityName)` so the
 * plugin file itself never imports host code (bundler-safe).
 */
function buildServerModule({ pluginId, resources, capabilityName }) {
  return {
    init(ctx) {
      for (const [resourceName, resource] of Object.entries(resources)) {
        const base = `/api/${pluginId}/${resourceName}`;
        if (typeof resource.list === 'string' || typeof resource.list === 'function') {
          ctx.registerRoute('GET', `${base}/list`, async (req, res) => {
            try {
              const dataApi = ctx.capabilities.use(capabilityName);
              const scope = dataApi[pluginId] || dataApi[resourceName] || dataApi;
              const fn = scope[resourceName] || scope.list || dataApi;
              const list = typeof resource.list === 'function'
                ? await resource.list(req, ctx)
                : await callCapabilityFn(ctx, capabilityName, resource.list, req);
              void fn;
              ctx.json(res, 200, { items: Array.isArray(list) ? list : [] });
            } catch (err) {
              ctx.json(res, 500, { error: err.message || String(err) });
            }
          });
        }
        if (resource.get) {
          ctx.registerRoute('GET', `${base}/:id`, async (req, res, params) => {
            try {
              const item = await callCapabilityFn(ctx, capabilityName, resource.get, req, params);
              ctx.json(res, 200, { item });
            } catch (err) {
              ctx.json(res, 500, { error: err.message || String(err) });
            }
          });
        }
        if (resource.update) {
          ctx.registerRoute('PATCH', `${base}/:id`, async (req, res, params) => {
            try {
              const body = await ctx.readBody(req);
              const item = await callCapabilityFn(ctx, capabilityName, resource.update, req, params, body);
              ctx.activity({ text: `${pluginId}/${resourceName} updated ${params.id}`, icon: '✏️', level: 'info' });
              ctx.json(res, 200, { item });
            } catch (err) {
              ctx.json(res, 500, { error: err.message || String(err) });
            }
          });
        }
      }
      ctx.log(`Pipeline plugin "${pluginId}" ready — serving existing admin data.`);
    },
  };
}

/** Resolve a capability reference like "orders.list" or ["orders","list"]. */
async function callCapabilityFn(ctx, capabilityName, ref, req, params, body) {
  const dataApi = ctx.capabilities.use(capabilityName);
  const limit = Number((req.searchParams && req.searchParams.get('limit')) || 200);
  if (typeof ref === 'function') return ref({ req, params, body, limit, dataApi });
  const trail = Array.isArray(ref) ? ref : String(ref).split('.');
  let fn = dataApi;
  for (const key of trail) fn = fn && fn[key];
  if (typeof fn !== 'function') throw new Error(`capability "${capabilityName}" has no function "${trail.join('.')}"`);
  return fn({ req, params, body, limit });
}

function buildManifest(pipeline) {
  const pluginId = escId(pipeline.id);
  const pagePath = (pipeline.page && pipeline.page.path) || pluginId;
  return {
    id: pluginId,
    name: pipeline.name || pluginId,
    version: pipeline.version || '0.1.0',
    description: pipeline.description || `Existing admin pipeline: ${pluginId}.`,
    icon: pipeline.icon || '🧩',
    category: pipeline.category || 'General',
    pages: pipeline.page === false ? [] : [{
      path: pagePath,
      title: (pipeline.page && pipeline.page.title) || pipeline.name || pluginId,
      icon: pipeline.icon || '📄',
      order: (pipeline.page && pipeline.page.order) || 50,
    }],
    widgets: pipeline.widget === false ? [] : [{
      slot: (pipeline.widget && pipeline.widget.slot) || 'dashboard.grid',
      id: `${pluginId}-summary`,
      order: (pipeline.widget && pipeline.widget.order) || 50,
    }],
    provides: [],
    requires: [],
  };
}

/**
 * Turn an array of existing-admin pipeline definitions into kernel options.
 * Returns `{ pluginDefs, serverModules, assets }`.
 */
function adaptExistingAdmin({ pipelines = [], capabilityName = 'site.data' } = {}) {
  const pluginDefs = [];
  const serverModules = {};
  const assets = {};
  for (const pipeline of pipelines) {
    const pluginId = escId(pipeline.id);
    const meta = buildManifest(pipeline);
    const serverModule = pipeline.serverModule || buildServerModule({
      pluginId,
      resources: pipeline.resources || {},
      capabilityName: pipeline.capabilityName || capabilityName,
    });
    const hasClient = pipeline.clientJs !== false;
    const clientJs = typeof pipeline.clientJs === 'string'
      ? pipeline.clientJs
      : buildClientJs({
        pluginId,
        page: meta.pages[0],
        resources: pipeline.resources || { items: {} },
        emptyHint: pipeline.emptyHint,
      });
    pluginDefs.push({ id: pluginId, meta, serverModule, hasClient });
    serverModules[pluginId] = serverModule;
    if (hasClient) {
      assets[`oa/plugins/${pluginId}/client.js`] = {
        content: clientJs,
        type: 'text/javascript; charset=utf-8',
      };
    }
  }
  return { pluginDefs, serverModules, assets };
}

module.exports = {
  adaptExistingAdmin,
  buildManifest,
  buildServerModule,
  buildClientJs,
  callCapabilityFn,
};
